### ISSUE TITLE
切换页面的时候排版乱了哦

### ISSUE THREAD

**Issue by clark-cui** [richshaw2015/oh-my-rss#1]

**Comment by richshaw2015** [comment]
具体是什么操作呢

**Comment by clark-cui** [comment]
chrome，版本76.左边的上下页，点击切换后。
![QVLVS2EB1X{%5LZHKMX7AZA](https://user-images.githubusercontent.com/46164858/64468895-64cf1480-d15c-11e9-907c-4e90b01e0884.png)

**Comment by richshaw2015** [comment]
新版本已经修复，麻烦刷新下页面。
