### ISSUE TITLE
求手机端适配

### ISSUE THREAD

**Issue by CosmosNing** [richshaw2015/oh-my-rss#2]
![IMG_20190906_170613](https://user-images.githubusercontent.com/30529795/64415931-ccd41b00-d0c8-11e9-9be5-4a2e7b4f2ee7.png)

手机端排版错误，希望能适配

**Comment by richshaw2015** [comment]
> ![IMG_20190906_170613](https://user-images.githubusercontent.com/30529795/64415931-ccd41b00-d0c8-11e9-9be5-4a2e7b4f2ee7.png)
> 
> 手机端排版错误，希望能适配

后续考虑适配移动端，现阶段以PC端为主~

**Comment by richshaw2015** [comment]
已经适配了
